site_name: Clojure LSP
site_description: Language Server Protocol Implementation for Clojure
site_url: https://clojure-lsp.github.io/clojure-lsp

repo_name: clojure-lsp/clojure-lsp
repo_url: https://github.com/clojure-lsp/clojure-lsp

nav:
  - Home: README.md
  - Settings: settings.md
  - Clients: clients.md
  - Capabilities: capabilities.md
  - Troubleshooting: troubleshooting.md
  - Support Us: https://opencollective.com/clojure-lsp

theme:
  name: material
  logo: images/logo-light.svg
  favicon: images/logo-light.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/clojure-lsp/clojure-lsp
    - icon: fontawesome/brands/slack
      link: https://clojurians.slack.com/archives/CPABC1H61

extra_css:
  - stylesheets/layout.css

markdown_extensions:
  - pymdownx.superfences
  - codehilite
  - meta
  - toc:
      permalink: '#'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
