name: Brew bump

on:
  push:
    tags:
      - '*'

jobs:
  bump:
    name: Update Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{secrets.BREW_GITHUB_TOKEN}}
          formula: clojure-lsp
