name: Bump Homebrew formula

on:
  push:
    tags: '2*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1.8
        with:
          # A PR will be sent to github.com/Homebrew/homebrew-core to update this formula:
          formula-name: clojure-lsp
        env:
          COMMITTER_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
