name: Release

on:
  push:
    branches:
      - master

jobs:
  tag:
    name: Tag new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        run: "bash release"

  release:
    name: Create Release
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.latest-tag.outputs.tag}}
          release_name: ${{ steps.latest-tag.outputs.tag}}

  build-binary:
    name: Build binary
    needs: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.3

      - name: Generate binary
        run: lein bin

      - uses: actions/upload-artifact@v1
        with:
          name: clojure-lsp
          path: target/clojure-lsp

  upload-binary:
    name: Upload Binary to release
    needs: build-binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v2
        with:
          name: clojure-lsp
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: clojure-lsp
          asset_name: clojure-lsp
          tag: ${{ steps.latest-tag.outputs.tag}}

  build-jar:
    name: Build jar
    needs: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.3

      - name: Generate jar
        run: lein uberjar

      - uses: actions/upload-artifact@v1
        with:
          name: clojure-lsp.jar
          path: target/clojure-lsp-${{ steps.latest-tag.outputs.tag}}-standalone.jar

  upload-jar:
    name: Upload jar to release
    needs: build-jar
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v2
        with:
          name: clojure-lsp.jar
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: clojure-lsp.jar
          asset_name: clojure-lsp.jar
          tag: ${{ steps.latest-tag.outputs.tag}}
