name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: Create Release
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

  build-binary:
    name: Build binary
    needs: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.3

      - name: Generate binary
        run: lein bin

      - uses: actions/upload-artifact@v1
        with:
          name: clojure-lsp
          path: target/clojure-lsp

  upload-binary:
    name: Upload Binary to release
    needs: build-binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: clojure-lsp
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.release.outputs.id }}
          args: 'clojure-lsp'
